### PR TITLE
Add package skeleton with devtools::create()

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
I've just taken a look at https://github.com/marcusyoung/opentripplanner/pull/1 - this is a much more conservative starting point. We should be cautious to avoid importing the kitchen sink and proceed slowly. This represents the minimum to get started I think. @marcusyoung you happy with this? suggest @mem48 build on this gradually if so so we can see what changes step-by-step.

**Comment by Robinlovelace** [comment]
Nudge @marcusyoung

**Comment by marcusyoung** [comment]
Bare with me. I'm just getting up to speed reading Hadley's 'R Packages' book so I know what this code is all about.

**Comment by Robinlovelace** [comment]
OK no problem. This is very minimal and provides a basis for you to build on. Good for you to be reading-up on this so you know what every part of this does.

**Comment by marcusyoung** [comment]
@Robinlovelace  I'm unclear why the files for the package skeleton are repeated. They are at the top level of the repository, but then there is another folder opentripplanner/opentripplanner where the files are repeated?

**Comment by Robinlovelace** [comment]
Seems so - not sure what happened there... Thanks for the review comments.

**Comment by Robinlovelace** [comment]
Can put in another one without that mistake if you like. Or feel free to fire away and I'll input. I spotted something dodgy with repeated files but thought it was just GitHub playing-up. Good test of the review process!

**Comment by marcusyoung** [comment]
I'll have a go putting my reading into practice!

**Comment by marcusyoung** [comment]
Ok, I've done an initial package setup, and incorporated some of the content that @mem48 included in his pull request in the readme and DESCRIPTION files. This has been a very useful exercise.

**Comment by Robinlovelace** [comment]
Great work. What's the next steps? Suggest documenting in the issue tracker.

**Pull request closed without merging**
